import streamlit as st
import pandas as pd
import sqlite3
import time

st.set_page_config(page_title="AIoT Live Dashboard", page_icon="📡", layout="wide")

DB_NAME = 'aiotdb.db'

@st.cache_data(ttl=1)  # Refresh cache frequently
def get_data():
    try:
        conn = sqlite3.connect(DB_NAME)
        query = "SELECT id, temp, humid, time, metadata FROM sensors ORDER BY id DESC LIMIT 50"
        df = pd.read_sql_query(query, conn)
        conn.close()
        return df
    except Exception as e:
        return pd.DataFrame()

st.title("📡 AIoT Real-Time Dashboard (Live Demo)")
st.markdown("This dashboard automatically loads and refreshes data generated by the ESP32 simulator.")

# Create an empty container that we will continuously update
placeholder = st.empty()

# Basic live-refresh loop
while True:
    df = get_data()

    with placeholder.container():
        if not df.empty:
            # Get latest row for KPIs
            latest = df.iloc[0]
            
            # --- KPIs Section ---
            col1, col2, col3 = st.columns(3)
            col1.metric("🌡️ Latest Temperature", f"{latest['temp']} °C")
            col2.metric("💧 Latest Humidity", f"{latest['humid']} %")
            col3.metric("🕒 Last Update (Taiwan Time)", f"{latest['time']}")
            
            st.divider()

            # --- Charts Section ---
            st.markdown("### 📈 Live Trends")
            
            # Prepare data for charting (reverse so chronological is left-to-right)
            chart_df = df.iloc[::-1].copy()
            if 'time' in chart_df.columns:
                chart_df['time'] = pd.to_datetime(chart_df['time'])
                chart_df.set_index('time', inplace=True)
            
            chart_col1, chart_col2 = st.columns(2)
            with chart_col1:
                st.subheader("Temperature History (°C)")
                st.line_chart(chart_df['temp'], color="#ff4b4b")
                
            with chart_col2:
                st.subheader("Humidity History (%)")
                st.line_chart(chart_df['humid'], color="#0068c9")
                
            st.divider()
                
            # --- Table Section ---
            st.markdown("### 📋 Recent Data Table")
            st.dataframe(df, use_container_width=True, hide_index=True)
            
        else:
            st.warning("⏳ Waiting for data... Ensure Flask server and esp32_generator are running.")
            
    # Refresh dashboard roughly every 2 seconds
    time.sleep(2)
